# Generated by Django 6.0.4 on 2026-04-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_registration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qr/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
